# Generated by Django 4.1.7 on 2023-04-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myQuery', models.CharField(max_length=35)),
                ('myName', models.CharField(max_length=60)),
                ('myEmail', models.CharField(max_length=60)),
                ('myPhone', models.CharField(max_length=10)),
                ('eligible', models.CharField(max_length=20)),
                ('mesg', models.CharField(max_length=20)),
            ],
        ),
    ]
